# Generated by Django 3.0.3 on 2020-02-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
